package com.sina.app.util;

public interface Constant {
	String TOPOLOGY_NAME_KEY = "TOPOLOGY_NAME";

	String CLICK_SPOUT_NUM = "CLICK_SPOUT_NUM";
	String IMPRESSION_SPOUT_NUM = "IMPRESSION_SPOUT_NUM";
	String CLICK_BOLT_NUM = "CLICK_BOLT_NUM";
	String IMPRESSION_BOLT_NUM = "IMPRESSION_BOLT_NUM";
	String INTERVAL_COUNT_BOLT_NUM = "INTERVAL_COUNT_BOLT_NUM";
	String REDIS_BOLT_NUM = "REDIS_BOLT_NUM";
	String OUTPUT_BOLT_NUM = "OUTPUT_BOLT_NUM";
	
	String WORKER_NUM_KEY = "WORKER_NUM";
	String MAX_PENDING_KEY = "MAX_PENDING";
	String ACK_NUM_KEY = "ACK_NUM";

	String KAFKA_CLICK_TOPIC = "KAFKA_CLICK_TOPIC";
	String KAFKA_IMPRESSION_TOPIC = "KAFKA_IMPRESSION_TOPIC";
	String KAFKA_CLICK_GROUP = "KAFKA_CLICK_GROUP";
	String KAFKA_IMPRESSION_GROUP = "KAFKA_IMPRESSION_GROUP";
	
	String KAFKA_ZK_KEY = "KAFKA_ZOOKEEPER";
	String KAFKA_CONSUMER_TIMEOUT_KEY = "KAFKA_CONSUMER_TIMEOUT_MS"; 

	String REDIS_LIST = "REDIS_LIST";

	String TRANSFER_BUFFER_SIZE_KEY = "TRNASFER_BUFFER_SIZE";
	String INTERVAL_COUNT_SECONDS = "INTERVAL_COUNT_SECONDS";
	
	String ALERT_KID = "ALERT_KID";
	String ALERT_PASSWORD = "ALERT_PASSWORD";
	String ALERT_GROUP_NAME = "ALERT_GROUP_NAME";
	String ALERT_SERVICE_NAME = "ALERT_SERVICE_NAME";
	String ALERT_MAIL_TO = "ALERT_MAIL_TO";
	String ALERT_MSG_TO = "ALERT_MSG_TO";
	
	String ALERT_FAILURE_THRESHOLD = "ALERT_FAILURE_THRESHOLD";
	String ALERT_CHECK_INTERVAL_SECONDS = "ALERT_CHECK_INTERVAL_SECONDS";

	/**
	 * broker list of output kafka
	 */
	String OUTPUT_KAFKA_BROKER_LIST = "OUTPUT_KAFKA_BROKER_LIST";
	/**
	 * topic of output kafka
	 */
	String OUTPUT_KAFKA_TOPIC = "OUTPUT_KAFKA_TOPIC";
}
