// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: table.proto

package ea.proto;

public final class TableOuterClass {
  private TableOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ea.proto.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string psid = 1;</code>
     */
    boolean hasPsid();
    /**
     * <code>required string psid = 1;</code>
     */
    java.lang.String getPsid();
    /**
     * <code>required string psid = 1;</code>
     */
    com.google.protobuf.ByteString
        getPsidBytes();

    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    boolean hasInfos();
    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    java.lang.String getInfos();
    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    com.google.protobuf.ByteString
        getInfosBytes();

    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    boolean hasOrder();
    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    java.lang.String getOrder();
    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderBytes();

    /**
     * <code>required int32 pv = 4;</code>
     */
    boolean hasPv();
    /**
     * <code>required int32 pv = 4;</code>
     */
    int getPv();

    /**
     * <code>required int32 clk = 5;</code>
     */
    boolean hasClk();
    /**
     * <code>required int32 clk = 5;</code>
     */
    int getClk();
  }
  /**
   * Protobuf type {@code ea.proto.Record}
   */
  public static final class Record extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ea.proto.Record)
      RecordOrBuilder {
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Record(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Record defaultInstance;
    public static Record getDefaultInstance() {
      return defaultInstance;
    }

    public Record getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Record(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              psid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              infos_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              order_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pv_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              clk_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ea.proto.TableOuterClass.internal_static_ea_proto_Record_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ea.proto.TableOuterClass.internal_static_ea_proto_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ea.proto.TableOuterClass.Record.class, ea.proto.TableOuterClass.Record.Builder.class);
    }

    public static com.google.protobuf.Parser<Record> PARSER =
        new com.google.protobuf.AbstractParser<Record>() {
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Record(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PSID_FIELD_NUMBER = 1;
    private java.lang.Object psid_;
    /**
     * <code>required string psid = 1;</code>
     */
    public boolean hasPsid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string psid = 1;</code>
     */
    public java.lang.String getPsid() {
      java.lang.Object ref = psid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          psid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string psid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPsidBytes() {
      java.lang.Object ref = psid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFOS_FIELD_NUMBER = 2;
    private java.lang.Object infos_;
    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    public boolean hasInfos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    public java.lang.String getInfos() {
      java.lang.Object ref = infos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          infos_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string infos = 2;</code>
     *
     * <pre>
     * other info of record except psid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getInfosBytes() {
      java.lang.Object ref = infos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        infos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_FIELD_NUMBER = 3;
    private java.lang.Object order_;
    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    public java.lang.String getOrder() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          order_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string order = 3;</code>
     *
     * <pre>
     * order of ad position
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderBytes() {
      java.lang.Object ref = order_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        order_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PV_FIELD_NUMBER = 4;
    private int pv_;
    /**
     * <code>required int32 pv = 4;</code>
     */
    public boolean hasPv() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 pv = 4;</code>
     */
    public int getPv() {
      return pv_;
    }

    public static final int CLK_FIELD_NUMBER = 5;
    private int clk_;
    /**
     * <code>required int32 clk = 5;</code>
     */
    public boolean hasClk() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 clk = 5;</code>
     */
    public int getClk() {
      return clk_;
    }

    private void initFields() {
      psid_ = "";
      infos_ = "";
      order_ = "";
      pv_ = 0;
      clk_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPsid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInfos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPsidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInfosBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pv_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, clk_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPsidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInfosBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOrderBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pv_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, clk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ea.proto.TableOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ea.proto.TableOuterClass.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ea.proto.TableOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ea.proto.TableOuterClass.Record prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ea.proto.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ea.proto.Record)
        ea.proto.TableOuterClass.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Record_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ea.proto.TableOuterClass.Record.class, ea.proto.TableOuterClass.Record.Builder.class);
      }

      // Construct using ea.proto.TableOuterClass.Record.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        psid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        infos_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        order_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        clk_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Record_descriptor;
      }

      public ea.proto.TableOuterClass.Record getDefaultInstanceForType() {
        return ea.proto.TableOuterClass.Record.getDefaultInstance();
      }

      public ea.proto.TableOuterClass.Record build() {
        ea.proto.TableOuterClass.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ea.proto.TableOuterClass.Record buildPartial() {
        ea.proto.TableOuterClass.Record result = new ea.proto.TableOuterClass.Record(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.psid_ = psid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.infos_ = infos_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.order_ = order_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pv_ = pv_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clk_ = clk_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ea.proto.TableOuterClass.Record) {
          return mergeFrom((ea.proto.TableOuterClass.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ea.proto.TableOuterClass.Record other) {
        if (other == ea.proto.TableOuterClass.Record.getDefaultInstance()) return this;
        if (other.hasPsid()) {
          bitField0_ |= 0x00000001;
          psid_ = other.psid_;
          onChanged();
        }
        if (other.hasInfos()) {
          bitField0_ |= 0x00000002;
          infos_ = other.infos_;
          onChanged();
        }
        if (other.hasOrder()) {
          bitField0_ |= 0x00000004;
          order_ = other.order_;
          onChanged();
        }
        if (other.hasPv()) {
          setPv(other.getPv());
        }
        if (other.hasClk()) {
          setClk(other.getClk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPsid()) {
          
          return false;
        }
        if (!hasInfos()) {
          
          return false;
        }
        if (!hasOrder()) {
          
          return false;
        }
        if (!hasPv()) {
          
          return false;
        }
        if (!hasClk()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ea.proto.TableOuterClass.Record parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ea.proto.TableOuterClass.Record) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object psid_ = "";
      /**
       * <code>required string psid = 1;</code>
       */
      public boolean hasPsid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string psid = 1;</code>
       */
      public java.lang.String getPsid() {
        java.lang.Object ref = psid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            psid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string psid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPsidBytes() {
        java.lang.Object ref = psid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          psid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string psid = 1;</code>
       */
      public Builder setPsid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        psid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string psid = 1;</code>
       */
      public Builder clearPsid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        psid_ = getDefaultInstance().getPsid();
        onChanged();
        return this;
      }
      /**
       * <code>required string psid = 1;</code>
       */
      public Builder setPsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        psid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object infos_ = "";
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public boolean hasInfos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public java.lang.String getInfos() {
        java.lang.Object ref = infos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            infos_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getInfosBytes() {
        java.lang.Object ref = infos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          infos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public Builder setInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        infos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public Builder clearInfos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        infos_ = getDefaultInstance().getInfos();
        onChanged();
        return this;
      }
      /**
       * <code>required string infos = 2;</code>
       *
       * <pre>
       * other info of record except psid
       * </pre>
       */
      public Builder setInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        infos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object order_ = "";
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public java.lang.String getOrder() {
        java.lang.Object ref = order_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            order_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderBytes() {
        java.lang.Object ref = order_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          order_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public Builder setOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        order_ = getDefaultInstance().getOrder();
        onChanged();
        return this;
      }
      /**
       * <code>required string order = 3;</code>
       *
       * <pre>
       * order of ad position
       * </pre>
       */
      public Builder setOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        order_ = value;
        onChanged();
        return this;
      }

      private int pv_ ;
      /**
       * <code>required int32 pv = 4;</code>
       */
      public boolean hasPv() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 pv = 4;</code>
       */
      public int getPv() {
        return pv_;
      }
      /**
       * <code>required int32 pv = 4;</code>
       */
      public Builder setPv(int value) {
        bitField0_ |= 0x00000008;
        pv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pv = 4;</code>
       */
      public Builder clearPv() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pv_ = 0;
        onChanged();
        return this;
      }

      private int clk_ ;
      /**
       * <code>required int32 clk = 5;</code>
       */
      public boolean hasClk() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 clk = 5;</code>
       */
      public int getClk() {
        return clk_;
      }
      /**
       * <code>required int32 clk = 5;</code>
       */
      public Builder setClk(int value) {
        bitField0_ |= 0x00000010;
        clk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clk = 5;</code>
       */
      public Builder clearClk() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clk_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ea.proto.Record)
    }

    static {
      defaultInstance = new Record(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ea.proto.Record)
  }

  public interface TableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ea.proto.Table)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    boolean hasAdtype();
    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    java.lang.String getAdtype();
    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    com.google.protobuf.ByteString
        getAdtypeBytes();

    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    boolean hasStattype();
    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    java.lang.String getStattype();
    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    com.google.protobuf.ByteString
        getStattypeBytes();

    /**
     * <code>required int64 ts = 3;</code>
     *
     * <pre>
     * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
     * </pre>
     */
    boolean hasTs();
    /**
     * <code>required int64 ts = 3;</code>
     *
     * <pre>
     * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
     * </pre>
     */
    long getTs();

    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    java.util.List<ea.proto.TableOuterClass.Record> 
        getDataList();
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    ea.proto.TableOuterClass.Record getData(int index);
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    int getDataCount();
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    java.util.List<? extends ea.proto.TableOuterClass.RecordOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    ea.proto.TableOuterClass.RecordOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ea.proto.Table}
   */
  public static final class Table extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ea.proto.Table)
      TableOrBuilder {
    // Use Table.newBuilder() to construct.
    private Table(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Table(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Table defaultInstance;
    public static Table getDefaultInstance() {
      return defaultInstance;
    }

    public Table getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Table(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              adtype_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              stattype_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ts_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                data_ = new java.util.ArrayList<ea.proto.TableOuterClass.Record>();
                mutable_bitField0_ |= 0x00000008;
              }
              data_.add(input.readMessage(ea.proto.TableOuterClass.Record.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ea.proto.TableOuterClass.internal_static_ea_proto_Table_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ea.proto.TableOuterClass.internal_static_ea_proto_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ea.proto.TableOuterClass.Table.class, ea.proto.TableOuterClass.Table.Builder.class);
    }

    public static com.google.protobuf.Parser<Table> PARSER =
        new com.google.protobuf.AbstractParser<Table>() {
      public Table parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Table(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Table> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ADTYPE_FIELD_NUMBER = 1;
    private java.lang.Object adtype_;
    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    public boolean hasAdtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    public java.lang.String getAdtype() {
      java.lang.Object ref = adtype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adtype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string adtype = 1;</code>
     *
     * <pre>
     * platform_ideatype
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAdtypeBytes() {
      java.lang.Object ref = adtype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATTYPE_FIELD_NUMBER = 2;
    private java.lang.Object stattype_;
    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    public boolean hasStattype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    public java.lang.String getStattype() {
      java.lang.Object ref = stattype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stattype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stattype = 2;</code>
     *
     * <pre>
     * type of statistic
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStattypeBytes() {
      java.lang.Object ref = stattype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stattype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 3;
    private long ts_;
    /**
     * <code>required int64 ts = 3;</code>
     *
     * <pre>
     * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
     * </pre>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 ts = 3;</code>
     *
     * <pre>
     * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
     * </pre>
     */
    public long getTs() {
      return ts_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private java.util.List<ea.proto.TableOuterClass.Record> data_;
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    public java.util.List<ea.proto.TableOuterClass.Record> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    public java.util.List<? extends ea.proto.TableOuterClass.RecordOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    public ea.proto.TableOuterClass.Record getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .ea.proto.Record data = 4;</code>
     *
     * <pre>
     * statistic result
     * </pre>
     */
    public ea.proto.TableOuterClass.RecordOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      adtype_ = "";
      stattype_ = "";
      ts_ = 0L;
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAdtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStattype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAdtypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStattypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, ts_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(4, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAdtypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStattypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ts_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ea.proto.TableOuterClass.Table parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Table parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ea.proto.TableOuterClass.Table parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ea.proto.TableOuterClass.Table parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ea.proto.TableOuterClass.Table prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ea.proto.Table}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ea.proto.Table)
        ea.proto.TableOuterClass.TableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Table_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Table_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ea.proto.TableOuterClass.Table.class, ea.proto.TableOuterClass.Table.Builder.class);
      }

      // Construct using ea.proto.TableOuterClass.Table.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        adtype_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        stattype_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ea.proto.TableOuterClass.internal_static_ea_proto_Table_descriptor;
      }

      public ea.proto.TableOuterClass.Table getDefaultInstanceForType() {
        return ea.proto.TableOuterClass.Table.getDefaultInstance();
      }

      public ea.proto.TableOuterClass.Table build() {
        ea.proto.TableOuterClass.Table result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ea.proto.TableOuterClass.Table buildPartial() {
        ea.proto.TableOuterClass.Table result = new ea.proto.TableOuterClass.Table(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.adtype_ = adtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stattype_ = stattype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ts_ = ts_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ea.proto.TableOuterClass.Table) {
          return mergeFrom((ea.proto.TableOuterClass.Table)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ea.proto.TableOuterClass.Table other) {
        if (other == ea.proto.TableOuterClass.Table.getDefaultInstance()) return this;
        if (other.hasAdtype()) {
          bitField0_ |= 0x00000001;
          adtype_ = other.adtype_;
          onChanged();
        }
        if (other.hasStattype()) {
          bitField0_ |= 0x00000002;
          stattype_ = other.stattype_;
          onChanged();
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000008);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAdtype()) {
          
          return false;
        }
        if (!hasStattype()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ea.proto.TableOuterClass.Table parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ea.proto.TableOuterClass.Table) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object adtype_ = "";
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public boolean hasAdtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public java.lang.String getAdtype() {
        java.lang.Object ref = adtype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            adtype_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAdtypeBytes() {
        java.lang.Object ref = adtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public Builder setAdtype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        adtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public Builder clearAdtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        adtype_ = getDefaultInstance().getAdtype();
        onChanged();
        return this;
      }
      /**
       * <code>required string adtype = 1;</code>
       *
       * <pre>
       * platform_ideatype
       * </pre>
       */
      public Builder setAdtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        adtype_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stattype_ = "";
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public boolean hasStattype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public java.lang.String getStattype() {
        java.lang.Object ref = stattype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stattype_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStattypeBytes() {
        java.lang.Object ref = stattype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stattype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public Builder setStattype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stattype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public Builder clearStattype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stattype_ = getDefaultInstance().getStattype();
        onChanged();
        return this;
      }
      /**
       * <code>required string stattype = 2;</code>
       *
       * <pre>
       * type of statistic
       * </pre>
       */
      public Builder setStattypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stattype_ = value;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>required int64 ts = 3;</code>
       *
       * <pre>
       * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
       * </pre>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 ts = 3;</code>
       *
       * <pre>
       * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
       * </pre>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required int64 ts = 3;</code>
       *
       * <pre>
       * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
       * </pre>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ts = 3;</code>
       *
       * <pre>
       * timestamp (seconds since 00:00 hours, Jan 1, 1970 UTC)
       * </pre>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<ea.proto.TableOuterClass.Record> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          data_ = new java.util.ArrayList<ea.proto.TableOuterClass.Record>(data_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ea.proto.TableOuterClass.Record, ea.proto.TableOuterClass.Record.Builder, ea.proto.TableOuterClass.RecordOrBuilder> dataBuilder_;

      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public java.util.List<ea.proto.TableOuterClass.Record> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public ea.proto.TableOuterClass.Record getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder setData(
          int index, ea.proto.TableOuterClass.Record value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder setData(
          int index, ea.proto.TableOuterClass.Record.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder addData(ea.proto.TableOuterClass.Record value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder addData(
          int index, ea.proto.TableOuterClass.Record value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder addData(
          ea.proto.TableOuterClass.Record.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder addData(
          int index, ea.proto.TableOuterClass.Record.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends ea.proto.TableOuterClass.Record> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public ea.proto.TableOuterClass.Record.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public ea.proto.TableOuterClass.RecordOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public java.util.List<? extends ea.proto.TableOuterClass.RecordOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public ea.proto.TableOuterClass.Record.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            ea.proto.TableOuterClass.Record.getDefaultInstance());
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public ea.proto.TableOuterClass.Record.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, ea.proto.TableOuterClass.Record.getDefaultInstance());
      }
      /**
       * <code>repeated .ea.proto.Record data = 4;</code>
       *
       * <pre>
       * statistic result
       * </pre>
       */
      public java.util.List<ea.proto.TableOuterClass.Record.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ea.proto.TableOuterClass.Record, ea.proto.TableOuterClass.Record.Builder, ea.proto.TableOuterClass.RecordOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ea.proto.TableOuterClass.Record, ea.proto.TableOuterClass.Record.Builder, ea.proto.TableOuterClass.RecordOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ea.proto.Table)
    }

    static {
      defaultInstance = new Table(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ea.proto.Table)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ea_proto_Record_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ea_proto_Record_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ea_proto_Table_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ea_proto_Table_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013table.proto\022\010ea.proto\"M\n\006Record\022\014\n\004psi" +
      "d\030\001 \002(\t\022\r\n\005infos\030\002 \002(\t\022\r\n\005order\030\003 \002(\t\022\n\n" +
      "\002pv\030\004 \002(\005\022\013\n\003clk\030\005 \002(\005\"U\n\005Table\022\016\n\006adtyp" +
      "e\030\001 \002(\t\022\020\n\010stattype\030\002 \002(\t\022\n\n\002ts\030\003 \002(\003\022\036\n" +
      "\004data\030\004 \003(\0132\020.ea.proto.Record"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ea_proto_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ea_proto_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ea_proto_Record_descriptor,
        new java.lang.String[] { "Psid", "Infos", "Order", "Pv", "Clk", });
    internal_static_ea_proto_Table_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ea_proto_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ea_proto_Table_descriptor,
        new java.lang.String[] { "Adtype", "Stattype", "Ts", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
